version: "3"

services:
  semantic_pr:
    build:
      context: .
      dockerfile: ../Dockerfile
    volumes:
      - ./semanticpr:/app/semanticpr
      - ./semanticpr.private-key.pem:/app/semanticpr.private-key.pem
    environment:
      - 'DEBUG=true'
      - 'SEMANTIC_APP_ID=40145'
      - 'ENV APP_ID=168662'
      - 'ENV WEBHOOK_PROXY_URL=https://semanticpr.shared.global.com/probot'
      #- 'PROCESS_INSTALLS_INTERVAL=30'
